version: '3'
services:
  microros:
    container_name: pysimcoder
    image: pysimcoder:latest
    volumes:
    - /dev:/dev
    - $XAUTHORITY:/tmp/.XAuthority
    - /home/bucher/ToDo/extradisk/ros_ws:/mnt
    environment:
    - DISPLAY
    - XAUTHORITY=/tmp/.XAuthority
    network_mode: host
    restart: always
    privileged: true
